language: rust
services: docker
matrix:
  fast_finish: true
  allow_failures:
  - env: RUSTFMT
  - env: CLIPPY
  include:
  - env: RUSTFMT
    rust: nightly
    before_script:
    - cargo install rustfmt-nightly --force
    script:
    - cargo fmt -- --write-mode=diff
  - env: CLIPPY
    rust: nightly
    before_script:
    - cargo install clippy --force
    script:
    - cargo clippy -- -D clippy-pedantic
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    rust: nightly
    os: osx
    osx_image: xcode9.2

script:
  - ci/run.sh

notifications:
  email:
    on_success: never
    on_failure: never
